### ISSUE TITLE
ImportError: No module named bashplotlib.histogram

### ISSUE THREAD

**Issue by wernight** [glamp/bashplotlib#30]
In a virtualenv:

    $ pip install bashplotlib
    $ ... | hist
    ...
    ImportError: No module named bashplotlib.histogram
   
Here is my environment on a *Ubuntu 12.04*:

    $ python --version
    Python 2.7.6
    $ pip --version
    pip 1.5.6 from /var/local/virtualenvs/ipython/local/lib/python2.7/site-packages (python 2.7)
    $ pip uninstall bashplotlib
    Uninstalling bashplotlib:
      /var/local/virtualenvs/ipython/bin/hist
      /var/local/virtualenvs/ipython/bin/scatter
      /var/local/virtualenvs/ipython/lib/python2.7/site-packages/bashplotlib-0.6.4-py2.7.egg-info

It looks like there should be directory `/var/local/virtualenvs/ipython/lib/python2.7/site-packages/bashplotlib` but there isn't.

**Comment by Aluriak** [comment]
Same problem here, with Archlinux and both Python 2 & 3.

Problem solved by installing from sources.

**Comment by yoavram** [comment]
Similar problem an Anaconda3, Py3.4, Win7 64-bit.
I get:
```sh
λ hist
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\hist-script.py", line 9, in <module>
    load_entry_point('bashplotlib==0.6.4', 'console_scripts', 'hist')()
  File "D:\Anaconda3\lib\site-packages\setuptools-18.5-py3.4.egg\pkg_resources\__init__.py", line 565, in load_entry_point
  File "D:\Anaconda3\lib\site-packages\setuptools-18.5-py3.4.egg\pkg_resources\__init__.py", line 2697, in load_entry_point
  File "D:\Anaconda3\lib\site-packages\setuptools-18.5-py3.4.egg\pkg_resources\__init__.py", line 2370, in load
  File "D:\Anaconda3\lib\site-packages\setuptools-18.5-py3.4.egg\pkg_resources\__init__.py", line 2376, in resolve
ImportError: No module named 'bashplotlib'
```

**Comment by jadijadi** [comment]
Same here, debian sid. 
[jadi@funlife ~]$ hist
Traceback (most recent call last):
  File "/usr/local/bin/hist", line 9, in <module>
    load_entry_point('bashplotlib==0.6.4', 'console_scripts', 'hist')()
  File "/home/jadi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jadi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/home/jadi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/home/jadi/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named bashplotlib.histogram
[jadi@funlife ~]$ python --version 
Python 2.7.11

**Comment by keevee09** [comment]
Same with OSX El Capitan and homebrew's Python 2.76 and 3.51.
    pip install bashplotlib
does not work
but installing from source as per the README.md
    git clone ...
    cd bashplotlib
    python setup.py install
works fine.

**Comment by MrZeusTheCoder** [comment]
Same here on Mavericks and Python 3.6.1 with `pip`: 
`Traceback (most recent call last):
  File "/Users/MrZeus/Desktop/SPIF_image_encryption/testy.py", line 90, in <module>
    print(bpl.histogram.__name__)
AttributeError: module 'bashplotlib' has no attribute 'histogram'` 
What's up @glamp?

**Comment by MrZeusTheCoder** [comment]
Installed from source, that fixed the issue, but the download almost 80MB! It took me over 10 minutes to download.
