### ISSUE TITLE
pip install produces IOError: [Errno 2] No such file or directory: 'LICENSE.txt'

### ISSUE THREAD

**Issue by dannyob** [glamp/bashplotlib#7]
Here's what I get!

pip 1.4.1 from /usr/lib/python2.7/dist-packages (python 2.7)

```
: minisub ~tmp%; pip install bashplotlib
Downloading/unpacking bashplotlib
  Downloading bashplotlib-0.5.1.tar.gz
  Running setup.py egg_info for package bashplotlib
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_danny/bashplotlib/setup.py", line 10, in <module>
        license=open("LICENSE.txt").read(),
    IOError: [Errno 2] No such file or directory: 'LICENSE.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_danny/bashplotlib/setup.py", line 10, in <module>

    license=open("LICENSE.txt").read(),

IOError: [Errno 2] No such file or directory: 'LICENSE.txt'
```

**Comment by Ruchika30** [comment]
what was the  solution ??
